[package]
name = "reproduction"
edition = "2021"
version = "0.1.0"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls"] }
futures = "0.3"

